[server]
# url = "https://127.0.0.1:8000"
# cert_path = "cert/cert.pem"
url = "https://127.0.0.1:8080"
cert_path = "../../../js_related/host-credential-manager-go/cert/cacert.pem"

[[target]]
hostname = 'myhost'
ip = '127.0.0.1'
username = 'worker'
